config/routes.rb
Rails.application.routes.draw do
  root to: 'question_sets#index'

  devise_for :users

  resources :questions, only: [:destroy, :new, :update]
  resources :question_sets do
    member do
      get 'test/size(/:size)' => 'question_sets#test'
      post 'result' => 'question_sets#result'
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :question_set
end

app/models/question_set.rb
class QuestionSet < ActiveRecord::Base
  belongs_to :user
  has_many :questions, dependent: :destroy

  def owner?(u)
    u && u == user
  end

  def destroy_all_questions!
    questions.each do |question|
      question.destroy
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :question_sets, :dependent => :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/question_sets_controller.rb
class QuestionSetsController < ApplicationController
  before_action :set_question_set, only: [:show, :edit, :update, :destroy]

  def show
  end

  def edit
  end

  def new
    @question_set = QuestionSet.new(user: current_user)
    # redirect_to action: 'edit', id: @question_set.id
  end

  def create
    @question_set = QuestionSet.new(title: params[:title], comment: params[:comment], user: current_user)

    (params[:texts] || []).each do |text|
      body = text.gsub(/<(.*?)>/, '_____')
      answer = text.scan(/<(.*?)>/).flatten.join(',')
      @question_set.questions << Question.create(body: body, answer: answer)
    end

    if @question_set.save
      redirect_to @question_set
    else
      render :new
    end
  end

  def update
    @question_set.assign_attributes(title: params[:title], comment: params[:comment])
    @question_set.destroy_all_questions!

    (params[:texts] || []).each do |text|
      body = text.gsub(/<(.*?)>/, '_____')
      answer = text.scan(/<(.*?)>/).flatten.join(',')
      @question_set.questions << Question.create(body: body, answer: answer)
    end

    @question_set.save

    redirect_to @question_set
  end

  def destroy
    @question_set.destroy

    redirect_to action: 'index'
  end

  def test
    @question_set = QuestionSet.find(params[:id])
    @targets = []

    blank_counts_max = params[:size].try(:to_i) || 114514
    blank_counts = 0

    @question_set.questions.order("RANDOM()").each do |question|
      @targets << question
      blank_counts += question.body.scan(/_____/).size
      break if blank_counts >= blank_counts_max
    end

    session[:question] = @targets.map { |t| t.id }
  end

  def result
    @question_set = QuestionSet.find(params[:id])
    hash = Question.find(session[:question]).map{ |model| [model.id, model] }.to_h # 該当する３つの文とIDを見つける（順番は適当）
    @targets = session[:question].map { |id| hash[id] } # 問題文の順番にmodelを並び変える
    @responses = @targets.map.with_index { |v, i| params[i.to_s] || [] } # テキストボックスの値を受け取る
  end

  private

  def set_question_set
    @question_set = QuestionSet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_sets_helper.rb
module QuestionSetsHelper
  def linebreak_to_br(text)
    return text if text.nil?
    h(text).gsub(/\r\n|\r|\n/, "<br>").html_safe
  end
  
  def count_match(a, b)
    [a, b].map(&:flatten).transpose.count do |pair|
      pair[0] == pair[1]
    end
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title 穴埋めの達人
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    #header
      = render "shared/header"
    #content.container      
      - if notice
        p.notice = notice
      - if alert
        p.alert = alert
      = yield
    #sidebar
      = render "shared/sidebar"
    #footer
      = render "shared/footer"

app/views/question_sets/_form.html.slim
- if @question_set.owner?(current_user)
  = form_tag @question_set, method: (@question_set.id ? :put : :post) do
  
    .input-group[style='margin-bottom: 30px']
       span.input-group-addon タイトル
       = text_field_tag :title, "#{@question_set.title}", class: 'form-control'

    .input-group[style='margin-bottom: 30px']
      span.input-group-addon コメント
      = text_field_tag :comment, "#{@question_set.comment}", class: 'form-control'
    
    p <←で囲まれた文字が問題の空白部分になります→>
    
    .table-responsive
      table#question-set-table.table.table-striped.table-bordered.table-hover
        thead
          tr
            th Body
            th Action
        tbody
          - @question_set.questions.each do |question, i|
            tr
              - text = question.body
              - question.answer.split(',').each do |answer|
                - text.sub!(/_____/, "<#{answer}>")
              td = text_area_tag 'texts[]', text, size: '130x3', style: 'resize: none', class: 'form-control question_text_field'
              td = button_tag 'Destroy', type: 'button', id: 'delete-question-button', class: 'btn btn-default delete'
    div.text-center[style='margin-bottom: 50px'] = button_tag '+1 Question', type: 'button', id: 'add-question-button', class: 'btn btn-lg btn-primary'
    div.text-center = submit_tag 'Update All Questions', class: 'btn btn-lg btn-success'

app/views/question_sets/edit.html.slim
- if @question_set.owner?(current_user)
  = form_tag @question_set, method: :put do
  
    .input-group[style='margin-bottom: 30px']
       span.input-group-addon タイトル
       = text_field_tag :title, "#{@question_set.title}", class: 'form-control'

    .input-group[style='margin-bottom: 30px']
      span.input-group-addon コメント
      = text_field_tag :comment, "#{@question_set.comment}", class: 'form-control'
    
    p <←で囲まれた文字が問題の空白部分になります→>
    
    .table-responsive
      table#question-set-table.table.table-striped.table-bordered.table-hover
        thead
          tr
            th Body
            th Action
        tbody
          - @question_set.questions.each do |question, i|
            tr
              - text = question.body
              - question.answer.split(',').each do |answer|
                - text.sub!(/_____/, "<#{answer}>")
              td = text_area_tag 'texts[]', text, size: '130x3', style: 'resize: none', class: 'form-control question_text_field'
              td = button_tag 'Destroy', type: 'button', id: 'delete-question-button', class: 'btn btn-default delete'
    div.text-center[style='margin-bottom: 50px'] = button_tag '+1 Question', type: 'button', id: 'add-question-button', class: 'btn btn-lg btn-primary'
    div.text-center = submit_tag 'Update All Questions', class: 'btn btn-lg btn-success'

app/views/question_sets/index.html.slim
.jumbotron
  h2 このサイトでできること
  p.lead
    | このサイトでは穴埋め問題を解いて採点することができます。
    | アカウントを作成することで、自分で問題集を作ることもできます。
    | ぜひ色々な問題を作ってみてください。

.table-responsive
  table.table.table-striped.table-bordered
    thead
      tr
        td タイトル
        td コメント
    tbody
      - QuestionSet.all.order(:title).each do |question_set|
        tr
          td = link_to question_set.title, question_set_path(question_set)
          td = question_set.comment

app/views/question_sets/new.html.slim
= render 'form'

app/views/question_sets/result.html.slim
= "#{@responses.inject(0) { |sum, r| sum + r.count }}問中"
= "#{count_match @responses, @targets.map { |t| t.answer.split(",") }}問正解しました"

.table-responsive
  table.table.table-striped.table-bordered
    tbody
      br
      - @targets.each_with_index do |question, i|
        tr
          td
            - answer = question.answer.split(",")
            - ss = (question.body + '_____$').split('_____')
            - ss.pop
            - ss.each_with_index do |s, j|
                = linebreak_to_br s
                - if j + 1 != ss.count
                  - if @responses[i][j] == answer[j]
                    span style="color: #01DF01"
                      = "[#{@responses[i][j]}]"
                  - else
                    span style="color: #FE2E2E" 
                      = "[(回答)#{@responses[i][j]}（解答）#{answer[j]}]"
= link_to "問題数選択に戻る", question_set_path(@question_set), class: "btn btn-lg btn-primary"

app/views/question_sets/show.html.slim
= link_to '問題集の一覧に戻る', question_sets_path, class: 'btn btn-link'

.jumbotron
  h1 = @question_set.title
  p.lead[style='padding-left: 50px'] = @question_set.comment

  - if @question_set.owner?(current_user)
    div[style='display:inline-flex; margin-top: 20px; margin-bottom: 20px']
        = button_to '問題集を編集する', edit_question_set_path(@question_set), method: :get, class: 'btn btn-primary'
        span[style='margin-left: 20px']
          = button_to '問題集を削除する', question_set_path(@question_set), method: :delete, class: 'btn btn-danger', data: { confirm: '本当に削除しますか？' }
  
  / TODO: button group にしたい
  .table-responsive
    table.table.table-striped.table-bordered
      tbody
        tr
          td = link_to '全問', controller: 'question_sets', action: 'test'
          - [80, 60, 40, 20].each do |size|
            td = link_to "#{size}問", controller: 'question_sets', action: 'test', size: size

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th Body
        th Answer
    tbody
      - @question_set.questions.each do |question|
        tr
          td = linebreak_to_br question.body 
          td = question.answer

app/views/question_sets/test.html.slim
= form_tag result_question_set_path(@question_set), method: :post do
  .table-responsive
    table.table.table-striped.table-bordered
      tbody
        - @targets.each_with_index do |question, i|
          tr
            td
              - ss = question.body + '_____$'
              - ss = ss.split('_____')
              - ss.pop
              - ss.each_with_index do |s, j|
                = linebreak_to_br s
                = text_field_tag i.to_s + "[]" unless j + 1 == ss.count
  = submit_tag "Submit", class: "btn btn-lg btn-success"

app/views/questions/result.html.slim
.container
  = "#{@responses.inject(0) { |sum, r| sum + r.count }}問中"
  = "#{count_match @responses, @targets.map { |t| t.answer.split(",") }}問正解しました"
  .table-responsive
    table.table.table-striped.table-bordered
      tbody
        br
        - @targets.each_with_index do |question, i|
          tr
            td
              - answer = question.answer.split(",")
              - ss = (question.body + '_____$').split('_____')
              - ss.pop
              - ss.each_with_index do |s, j|
                  = linebreak_to_br s
                  - if j + 1 != ss.count
                    - if @responses[i][j] == answer[j]
                      span style="color: #01DF01"
                        = "[#{@responses[i][j]}]"
                    - else
                      span style="color: #FE2E2E" 
                        = "[(回答)#{@responses[i][j]}（解答）#{answer[j]}]"
  = link_to "問題数選択に戻る", "/home/select", class: "btn btn-lg btn-primary"

app/views/questions/test.html.slim
.container
  = form_tag :result_questions, method: :post do
    .table-responsive
      table.table.table-striped.table-bordered
        tbody
          - @targets.each_with_index do |question, i|
            tr
              td
                - ss = question.body + '_____$'
                - ss = ss.split('_____')
                - ss.pop
                - ss.each_with_index do |s, j|
                  = linebreak_to_br s
                  = text_field_tag i.to_s + "[]" unless j + 1 == ss.count
    = submit_tag "Submit", class: "btn btn-lg btn-success"

app/views/shared/_footer.html.slim
footer.footer.navbar-fixed-bottom
  .container
    p.text-muted Copyright © 2016 kagamiz siquare meu All Rights Reserved.

app/views/shared/_header.html.slim
nav.navbar.navbar-default
  .container
    .navbar-header
      a.navbar-brand href="#{root_path}" 穴埋めの達人
    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle[data-toggle="dropdown" role="button"]
              | メニュー
              span.caret
            ul.dropdown-menu
              li
                a href="#{new_question_set_path}" 問題集の作成
              li
                a href="#{edit_user_registration_path}" 設定
              li.divider role="separator" 
              li
                a href="#{destroy_user_session_path}" ログアウト
        - else
          li
            = link_to "ログイン", new_user_session_path
          li
            = link_to "ユーザ登録", new_user_registration_path